### ISSUE TITLE
W/ActivityThread(16564): handleWindowVisibility: no activity for token android.os.BinderProxy@cd66bb

### ISSUE THREAD

**Issue by BigData-SmallMind** [0maru/twitter_login#114]
## Bug report

The device on which the app is run: POCOPHONE F1
Android 10

package version:  from pubspec.lock
` twitter_login:
dependency: "direct main"
description:
name: twitter_login
url: "https://pub.dartlang.org"
source: hosted
version: "4.3.1"`

The twitter auth screen opens up, and when I input the twitter credential,  press Authorize App I get redirected to the App without successfully getting the twitter data of the user.

---

## Additional context
In place of every "PACKAGE NAME" is the  inverted domain name of the package, eg:  com.companyname.appname

`I/Timeline(16564): Timeline: Activity_launch_request time:575498266
W/ActivityThread(16564): handleWindowVisibility: no activity for token android.os.BinderProxy@cd66bb
D/ForceDarkHelper(16564): updateByCheckExcludeList: pkg: <PACKAGE NAME> activity: com.maru.twitter_login.chrome_custom_tabs.ChromeCustomTabsActivity@126c2aa
I/Timeline(16564): Timeline: Activity_launch_request time:575498391
D/AndroidRuntime(16564): Shutting down VM
E/AndroidRuntime(16564): FATAL EXCEPTION: main
E/AndroidRuntime(16564): Process: <PACKAGE NAME>, PID: 16564
E/AndroidRuntime(16564): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{<PACKAGE NAME>/com.linusu.flutter_web_auth_2.CallbackActivity}: java.lang.ClassNotFoundException: Didn't find class "com.linusu.flutter_web_auth_2.CallbackActivity" on path: DexPathList[[zip file "/data/app/<PACKAGE NAME>-eT0RbBL1MnMxC4LtVyACbg==/base.apk"],nativeLibraryDirectories=[/data/app/<PACKAGE NAME>-eT0RbBL1MnMxC4LtVyACbg==/lib/arm64, /data/app/<PACKAGE NAME>-eT0RbBL1MnMxC4LtVyACbg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
E/AndroidRuntime(16564): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3232)
E/AndroidRuntime(16564): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
E/AndroidRuntime(16564): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime(16564): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(16564): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(16564): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
E/AndroidRuntime(16564): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(16564): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(16564): 	at android.app.ActivityThread.main(ActivityThread.java:7562)
E/AndroidRuntime(16564): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16564): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(16564): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(16564): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.linusu.flutter_web_auth_2.CallbackActivity" on path: DexPathList[[zip file "/data/app/<PACKAGE NAME>-eT0RbBL1MnMxC4LtVyACbg==/base.apk"],nativeLibraryDirectories=[/data/app/<PACKAGE NAME>-eT0RbBL1MnMxC4LtVyACbg==/lib/arm64, /data/app/<PACKAGE NAME>-eT0RbBL1MnMxC4LtVyACbg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
E/AndroidRuntime(16564): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
E/AndroidRuntime(16564): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(16564): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(16564): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E/AndroidRuntime(16564): 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
E/AndroidRuntime(16564): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1251)
E/AndroidRuntime(16564): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3220)
E/AndroidRuntime(16564): 	... 11 more
I/Process (16564): Sending signal. PID: 16564 SIG: 9`

---

### Flutter doctor

<details><summary>Click To Expand</summary>

[✓] Flutter (Channel stable, 3.3.10, on macOS 12.0.1 21A559 darwin-x64, locale en-EG)                                              Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

</details>

---

### Which method do you use?

- [x] login()

- [] loginV2()

**Comment by 0maru** [comment]
Hi @BigData-SmallMind 
Are you using `flutter_web_auth_2`?

The error is also occurring in flutter_web_auth_2, so please correct the error once and share error log again.

```
java.lang.ClassNotFoundException: Didn't find class "com.linusu.flutter_web_auth_2.CallbackActivity" on path: DexPathList[[zip file "/data/app/<PACKAGE NAME>-eT0RbBL1MnMxC4LtVyACbg==/base.apk"]
```

```
java.lang.ClassNotFoundException: Didn't find class "com.linusu.flutter_web_auth_2.CallbackActivity" on path: DexPathList[[zip file "/data/app/<PACKAGE NAME>-eT0RbBL1MnMxC4LtVyACbg==/base.apk"]
```

**Comment by BigData-SmallMind** [comment]
Hey. Yes I figured after checking my AndroidManifest and removing the intent filter that contained "com.linusu.flutter_web_auth_2.CallbackActivity" has solved the problem, thank you!

**Comment by 0maru** [comment]
OK.
This issue is closed.
